module.exports = {
  plugins: [
    require('@fullhuman/postcss-purgecss')({
      // 1. Tell PurgeCSS where to find your HTML files (Jekyll output)
      content: [
        './_site/**/*.html',
        './_site/*.html',
      ],

      // 2. Tell PurgeCSS what CSS files to analyze and clean
      css: [
        './_site/assets/css/bootstrap.min.css',
        './_site/assets/css/style.css',
      ],

      // 3. Define the default extractors (for complex selectors, especially those generated by JS frameworks)
      // This is essential for Tailwind/Bootstrap to prevent removal of utility classes
      defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || [],
      
      // 4. Safelist: Protect specific class names from being removed
      // These are classes dynamically added by JS (e.g., Snipcart, Bootstrap's modal/carousel)
      safelist: {
        standard: [
          'snipcart', // Protect all Snipcart related classes
          'carousel', // Protect Bootstrap Carousel classes
          'modal',    // Protect Bootstrap Modal classes
          'dropdown', // Protect Bootstrap Dropdown classes
          'show',     // Class often toggled by JS
          'fade',     // Class often toggled by JS
          'active',   // Class often toggled by JS
          // Add any other classes you see disappearing that are crucial
        ],
        // You can add patterns if you need to protect groups of classes
        // deep: [/regex-for-dynamic-classes/],
      },
    })
  ]
}